/**
 * Metadatos educativos + imágenes por producto — demo Sala Cero futuro
 * Basado en buenas prácticas Google (contenido claro, jerarquía, CTA visible)
 */
window.SALA_CERO_PRODUCTOS = {
  bySlug: {},
  byName: {},
};

(function () {
  var items = [
    {
      slug: "web-express",
      catalogName: "Web Express",
      title: "Sala Cero Web Express",
      category: "web",
      image: "./assets/catalog/web-express.jpg",
      demoUrl: "./demos/web-express/",
      whatIs: "Una página web de una sola pantalla con la información esencial de tu negocio: quién sos, qué ofrecés, fotos y un botón directo a WhatsApp.",
      whyChoose: "Es la forma más rápida y económica de tener presencia online profesional. Ideal si recién empezás o necesitás algo listo en 2 días.",
      pros: ["Precio accesible desde Bs 990", "Lista en 2 días", "Sin servidor mensual (Bs 0)", "Perfecta para validar tu negocio online"],
      sections: [
        { title: "Hero con foto", why: "Google recomienda que en los primeros 3 segundos el visitante entienda qué hacés. Una foto grande + titular claro cumple eso." },
        { title: "Servicios o productos", why: "Lista escaneable: el usuario no lee bloques largos, busca lo que necesita." },
        { title: "Botón WhatsApp fijo", why: "En Bolivia el cierre de venta pasa por WhatsApp. Un CTA visible reduce fricción." },
      ],
    },
    {
      slug: "landing-page",
      catalogName: "Landing page",
      title: "Sala Cero Landing",
      category: "web",
      image: "./assets/catalog/landing-page.jpg",
      demoUrl: "./demos/landing/",
      whatIs: "Una página diseñada para un solo objetivo: que el visitante te escriba, deje sus datos o pida una cotización.",
      whyChoose: "Cuando tenés una campaña, un producto nuevo o un evento, una landing convierte mejor que un sitio completo porque no distrae.",
      pros: ["Textos escritos por nosotros", "Formulario + WhatsApp", "Medición de visitas incluida", "Diseño propio, no plantilla genérica"],
      sections: [
        { title: "Titular + beneficio", why: "Una sola promesa clara arriba. Google Search Central: el titular debe responder qué gana el usuario." },
        { title: "Prueba social", why: "Testimonios o logos generan confianza antes del contacto." },
        { title: "Formulario corto", why: "Menos campos = más conversiones. Solo lo necesario para contactarte." },
        { title: "CTA repetido", why: "Quien scrollea hasta abajo también debe poder actuar sin volver arriba." },
      ],
    },
    {
      slug: "sitio-institucional",
      catalogName: "Sitio institucional",
      title: "Sala Cero Institucional",
      category: "web",
      image: "./assets/catalog/sitio-institucional.jpg",
      demoUrl: "./demos/institucional/",
      whatIs: "El sitio completo de tu empresa: servicios, equipo, noticias, contacto y hasta 8 secciones navegables.",
      whyChoose: "Para empresas que ya tienen trayectoria y necesitan transmitir seriedad, estructura y SEO básico.",
      pros: ["Hasta 8 páginas", "Blog o noticias", "SEO base incluido", "Formularios en cada sección clave"],
      sections: [
        { title: "Menú de navegación", why: "Estructura clara ayuda a Google a indexar y al usuario a encontrar información." },
        { title: "Sobre nosotros", why: "Humaniza la marca: quién está detrás genera confianza B2B y B2C." },
        { title: "Servicios detallados", why: "Cada servicio con su propia explicación mejora posicionamiento por palabras clave." },
        { title: "Contacto multipunto", why: "Formulario, mapa, teléfono y WhatsApp: distintos usuarios prefieren distintos canales." },
      ],
    },
    {
      slug: "catalogo-digital",
      catalogName: "Catálogo digital",
      title: "Sala Cero Catálogo",
      category: "web",
      image: "./assets/catalog/catalogo-digital.jpg",
      demoUrl: "./demos/catalogo/",
      whatIs: "Tus productos online con fotos, precios, categorías y buscador. El pedido se cierra por WhatsApp con el carrito armado.",
      whyChoose: "No necesitás pasarela de pago para empezar a vender. Muchos negocios en Bolivia cierran por WhatsApp y esto acelera ese flujo.",
      pros: ["Buscador y categorías", "100 productos cargados al inicio", "Panel para que cargues vos después", "Sin comisión por venta"],
      sections: [
        { title: "Grid de productos", why: "Patrón visual que el usuario ya conoce de Instagram y marketplaces." },
        { title: "Ficha de producto", why: "Foto grande, precio claro y descripción: todo lo necesario para decidir." },
        { title: "Carrito → WhatsApp", why: "El cliente manda el pedido armado; vos solo confirmás y cobrás." },
      ],
    },
    {
      slug: "paquete-ecommerce",
      catalogName: "Paquete E-commerce",
      title: "Sala Cero E-commerce",
      category: "web",
      image: "./assets/catalog/paquete-ecommerce.jpg",
      demoUrl: "./demos/ecommerce/",
      whatIs: "Tienda online completa con carrito, checkout y panel de administración. Preparada para conectar pagos cuando quieras.",
      whyChoose: "Para negocios listos para vender 24/7 con proceso de compra formal, inventario y reportes.",
      pros: ["Carrito y checkout", "Panel de productos", "Preparada para pagos", "100 productos iniciales incluidos"],
      sections: [
        { title: "Home con destacados", why: "Promociones y categorías visibles aumentan ticket promedio." },
        { title: "Carrito persistente", why: "El usuario puede seguir comprando sin perder lo elegido." },
        { title: "Checkout guiado", why: "Pasos claros reducen abandono — práctica estándar en Shopify y Google Merchant." },
        { title: "Panel admin", why: "Vos controlás stock, precios y pedidos sin depender de nadie." },
      ],
    },
    {
      slug: "ecommerce-medida",
      catalogName: "E-commerce a medida",
      title: "Sala Cero E-commerce Pro",
      category: "web",
      image: "./assets/catalog/ecommerce-medida.jpg",
      demoUrl: "./demos/ecommerce-pro/",
      whatIs: "Tienda construida alrededor de cómo funciona tu operación: reglas de envío, inventario conectado, pagos e integraciones.",
      whyChoose: "Cuando un paquete estándar no alcanza y necesitás flujos propios, reportes avanzados o conexión con tu ERP.",
      pros: ["Diseño desde cero", "Integración de pagos", "Inventario conectado", "Reportes de venta personalizados"],
      sections: [
        { title: "Flujo de compra custom", why: "Adaptado a tu logística: retiro en tienda, envío por zona, etc." },
        { title: "Integraciones", why: "Pagos, courier o contabilidad conectados a una sola fuente de verdad." },
        { title: "Dashboard de ventas", why: "Decisiones con datos: qué vende, cuándo y dónde." },
      ],
    },
    {
      slug: "base-sistema",
      catalogName: "Base del sistema",
      title: "Sala Cero Sistema — Base",
      category: "sistemas",
      image: "./assets/catalog/base-sistema.jpg",
      demoUrl: null,
      whatIs: "El núcleo de software sobre el que se montan inventario, ventas, CRM y demás módulos. Usuarios, permisos y panel central.",
      whyChoose: "Empezás por una base sólida y sumás módulos solo cuando los necesitás, sin pagar por lo que no usás.",
      pros: ["Usuarios y roles", "Panel centralizado", "Acceso desde cualquier PC", "Capacitación incluida"],
      sections: [
        { title: "Login seguro", why: "Cada persona ve solo lo que le corresponde." },
        { title: "Dashboard", why: "Resumen del negocio al abrir — patrón estándar en ERP y SaaS." },
      ],
    },
    {
      slug: "app-escritorio",
      catalogName: "App de escritorio",
      title: "Sala Cero Escritorio",
      category: "sistemas",
      image: "./assets/catalog/app-escritorio.jpg",
      demoUrl: null,
      whatIs: "El mismo sistema web, empaquetado como aplicación de escritorio para Windows, Linux o Mac.",
      whyChoose: "Ícono en el escritorio, abre sin navegador y se siente como programa instalado — ideal para cajeros y mostrador.",
      pros: ["Windows, Linux y Mac", "Se actualiza sola", "Sin abrir Chrome", "Misma data que el sistema web"],
      sections: [{ title: "Acceso directo", why: "Menos pasos para el equipo = menos errores y más velocidad." }],
    },
    {
      slug: "inventario",
      catalogName: "Inventario",
      title: "Sala Cero Inventario",
      category: "sistemas",
      image: "./assets/catalog/inventario.jpg",
      demoUrl: null,
      whatIs: "Control de stock: entradas, salidas, alertas de stock bajo, múltiples depósitos e historial.",
      whyChoose: "Saber qué tenés y dónde evita quiebres de stock y pérdidas por descontrol.",
      pros: ["Alertas automáticas", "Varios depósitos", "Historial completo", "Se conecta a ventas"],
      sections: [{ title: "Stock en tiempo real", why: "Lo que vendés descuenta automáticamente — sin Excel paralelo." }],
    },
    {
      slug: "pedidos-ventas",
      catalogName: "Pedidos y ventas",
      title: "Sala Cero Pedidos",
      category: "sistemas",
      image: "./assets/catalog/pedidos-ventas.jpg",
      demoUrl: null,
      whatIs: "Gestión del pedido desde que entra hasta que se entrega, con estados y comprobantes.",
      whyChoose: "Visibilidad del pipeline de ventas: quién pidió, en qué estado está y qué falta.",
      pros: ["Estados de avance", "Vinculado a inventario", "Comprobantes", "Historial por cliente"],
      sections: [{ title: "Kanban de estados", why: "Patrón visual para equipos: pendiente → preparando → entregado." }],
    },
    {
      slug: "caja-reportes",
      catalogName: "Caja y reportes",
      title: "Sala Cero Caja",
      category: "sistemas",
      image: "./assets/catalog/caja-reportes.jpg",
      demoUrl: null,
      whatIs: "Apertura y cierre de caja, ingresos, egresos y reportes exportables a Excel.",
      whyChoose: "Saber cuánto entró y salió, por período y por concepto, sin hojas sueltas.",
      pros: ["Cierre diario", "Exportar Excel", "Reportes por fecha", "Ingresos vs egresos"],
      sections: [{ title: "Cierre de caja", why: "Práctica contable básica que todo negocio físico necesita." }],
    },
    {
      slug: "clientes-crm",
      catalogName: "Clientes / CRM",
      title: "Sala Cero CRM",
      category: "sistemas",
      image: "./assets/catalog/clientes-crm.jpg",
      demoUrl: null,
      whatIs: "Ficha por cliente, historial de compras, seguimiento de contactos y segmentación.",
      whyChoose: "Vender de nuevo a quien ya compró es más barato que captar clientes nuevos.",
      pros: ["Historial de compras", "Segmentación", "Seguimiento de contactos", "Ficha completa"],
      sections: [{ title: "Perfil de cliente", why: "Contexto antes de llamar: qué compró, cuándo y cuánto." }],
    },
    {
      slug: "integracion-externa",
      catalogName: "Integración externa",
      title: "Sala Cero Integraciones",
      category: "sistemas",
      image: "./assets/catalog/integracion-externa.jpg",
      demoUrl: null,
      whatIs: "Conectar tu sistema con otra herramienta: pagos, courier, contabilidad o lo que ya uses.",
      whyChoose: "Evita cargar dos veces la misma información. Una sola fuente de verdad.",
      pros: ["Una integración por precio", "Documentada", "Pruebas incluidas", "Pagos, courier o contabilidad"],
      sections: [{ title: "API conectada", why: "Estándar de la industria: sistemas que hablan entre sí." }],
    },
    {
      slug: "app-interna",
      catalogName: "App interna",
      title: "Sala Cero App Interna",
      category: "apps",
      image: "./assets/catalog/app-interna.jpg",
      demoUrl: "./demos/apps/interna/",
      expoUrl: null,
      whatIs: "App móvil para tu equipo: pedidos, tareas, reportes y acceso al sistema desde el celular.",
      whyChoose: "Vendedores en calle, repartidores o gerentes que necesitan info en movimiento.",
      pros: ["Roles y permisos", "Funciona con datos móviles", "Conectada a tu sistema", "Android e iOS"],
      sections: [
        { title: "Login del equipo", why: "Solo personal autorizado accede a data sensible." },
        { title: "Lista de tareas", why: "Patrón móvil estándar: qué hay que hacer hoy." },
        { title: "Sync en la nube", why: "Lo que hace el vendedor en calle se ve en la oficina al instante." },
      ],
    },
    {
      slug: "app-catalogo",
      catalogName: "App de catálogo",
      title: "Sala Cero App Catálogo",
      category: "apps",
      image: "./assets/catalog/app-catalogo.jpg",
      demoUrl: "./demos/apps/catalogo/",
      expoUrl: null,
      whatIs: "Tu negocio en el celular del cliente: catálogo con fotos, pedido por WhatsApp y notificaciones.",
      whyChoose: "Presencia en el bolsillo del cliente, sin depender de que abra el navegador.",
      pros: ["Android e iOS", "Notificaciones push", "Catálogo con fotos", "Pedido por WhatsApp"],
      sections: [
        { title: "Tab bar inferior", why: "Patrón iOS/Android Material: navegación con el pulgar." },
        { title: "Catálogo swipeable", why: "Scroll vertical infinito — igual que Instagram Shopping." },
      ],
    },
    {
      slug: "app-reservas",
      catalogName: "App de reservas",
      title: "Sala Cero App Reservas",
      category: "apps",
      image: "./assets/catalog/app-reservas.jpg",
      demoUrl: "./demos/apps/reservas/",
      expoUrl: null,
      whatIs: "Agendar citas, turnos o mesas desde el celular con calendario y recordatorios.",
      whyChoose: "Elimina llamadas de confirmación y reduce no-shows con recordatorios automáticos.",
      pros: ["Calendario visual", "Recordatorios", "Panel para tu equipo", "Reserva 24/7"],
      sections: [
        { title: "Selector de fecha/hora", why: "UX estándar de Calendly, Google Calendar y apps de salones." },
        { title: "Confirmación", why: "Feedback inmediato al usuario: su turno quedó registrado." },
      ],
    },
    {
      slug: "app-seguimiento",
      catalogName: "App con seguimiento",
      title: "Sala Cero App Delivery",
      category: "apps",
      image: "./assets/catalog/app-seguimiento.jpg",
      demoUrl: "./demos/apps/seguimiento/",
      expoUrl: null,
      whatIs: "Delivery y rutas con mapa en vivo, app para repartidores y panel de control.",
      whyChoose: "Cuando la logística es crítica: el cliente ve dónde está su pedido.",
      pros: ["Mapa en vivo", "App repartidor", "Panel de control", "Rutas optimizadas"],
      sections: [
        { title: "Mapa de seguimiento", why: "Patrón Rappi, Uber Eats: reduce llamadas de dónde está mi pedido." },
        { title: "Estado del envío", why: "Timeline claro: preparando → en camino → entregado." },
      ],
    },
    {
      slug: "publicacion-tiendas",
      catalogName: "Publicación en tiendas",
      title: "Sala Cero — App Store & Play",
      category: "apps",
      image: "./assets/catalog/publicacion-tiendas.jpg",
      demoUrl: "./demos/apps/publicacion/",
      expoUrl: null,
      whatIs: "Servicio para dejar tu app publicada en Google Play y App Store: ficha, capturas, textos y envío a revisión.",
      whyChoose: "Publicar en tiendas tiene reglas técnicas y de contenido. Nosotros lo hacemos por vos.",
      pros: ["Capturas y textos", "Envío a revisión", "Pago único", "Cumple guidelines Apple/Google"],
      sections: [
        { title: "Ficha de la tienda", why: "Google Play Console y App Store Connect exigen descripción, ícono y screenshots específicos." },
      ],
    },
    {
      slug: "chatbot-whatsapp",
      catalogName: "Chatbot para WhatsApp",
      title: "Sala Cero Chatbot WhatsApp",
      category: "otros",
      image: "./assets/catalog/chatbot-whatsapp.jpg",
      demoUrl: null,
      whatIs: "Bot que responde precios, horarios y preguntas frecuentes en WhatsApp las 24 horas.",
      whyChoose: "No perdés consultas de madrugada o cuando estás ocupado atendiendo.",
      pros: ["Sin cobro por conversación", "Pasa a humano cuando hace falta", "Toma pedidos", "Responde FAQs"],
      sections: [{ title: "Menú de opciones", why: "Flujo guiado: el cliente elige sin escribir mucho." }],
    },
    {
      slug: "chatbot-ia",
      catalogName: "Chatbot con IA",
      title: "Sala Cero Chatbot IA",
      category: "otros",
      image: "./assets/catalog/chatbot-ia.jpg",
      demoUrl: null,
      whatIs: "Bot que entiende texto libre, entrenado con tu información, no solo botones.",
      whyChoose: "Cuando las preguntas son variadas y un menú rígido no alcanza.",
      pros: ["Entiende lenguaje natural", "Entrenado con tu info", "Toma pedidos completos", "Aprende de consultas"],
      sections: [{ title: "Conversación natural", why: "El cliente escribe como hablaría con una persona." }],
    },
    {
      slug: "chatbot-redes",
      catalogName: "Chatbot para redes",
      title: "Sala Cero Chatbot Multicanal",
      category: "otros",
      image: "./assets/catalog/chatbot-redes.jpg",
      demoUrl: null,
      whatIs: "Un solo bot atendiendo WhatsApp, Instagram, Facebook y Telegram desde una bandeja.",
      whyChoose: "Tus clientes están en distintas redes; vos respondés desde un solo lugar.",
      pros: ["4 canales en uno", "Una sola bandeja", "Reportes de consultas", "Comentarios y DMs"],
      sections: [{ title: "Bandeja unificada", why: "Patrón de herramientas como ManyChat y Respond.io." }],
    },
    {
      slug: "automatizacion-tareas",
      catalogName: "Automatización de tareas",
      title: "Sala Cero Automatización",
      category: "otros",
      image: "./assets/catalog/automatizacion-tareas.jpg",
      demoUrl: null,
      whatIs: "Tareas repetitivas hechas solas: cargar datos, reportes automáticos, avisos y conexiones entre herramientas.",
      whyChoose: "Libera horas de trabajo manual que hoy alguien hace a mano cada semana.",
      pros: ["Reportes automáticos", "Avisos por eventos", "Conecta herramientas", "Sin intervención manual"],
      sections: [{ title: "Triggers y acciones", why: "Si pasa X, hacer Y — lógica estándar de Zapier/Make." }],
    },
    {
      slug: "asistente-ia",
      catalogName: "Asistente con IA",
      title: "Sala Cero Asistente IA",
      category: "otros",
      image: "./assets/catalog/asistente-ia.jpg",
      demoUrl: null,
      whatIs: "Asistente entrenado con tus documentos, precios y forma de trabajar. Para clientes o para tu equipo.",
      whyChoose: "Respuestas consistentes basadas en tu info real, no inventadas.",
      pros: ["Aprende de tus archivos", "Para clientes o equipo", "Conectado a tu sistema", "Responde como tu negocio"],
      sections: [{ title: "Base de conocimiento", why: "Subís PDFs, precios y políticas; el asistente cita esa info." }],
    },
    {
      slug: "ecommerce-exportador",
      catalogName: "Paquete E-commerce Exportador",
      title: "Sala Cero Exportador",
      category: "otros",
      image: "./assets/catalog/ecommerce-exportador.jpg",
      demoUrl: "./demos/ecommerce/",
      whatIs: "Paquete completo para vender al exterior: tienda, piezas de lanzamiento y lineamientos de packaging.",
      whyChoose: "Todo junto para dar el salto internacional sin armar piezas sueltas.",
      pros: ["Tienda completa", "Piezas de lanzamiento", "Packaging guidelines", "Lista para operador logístico"],
      sections: [
        { title: "Tienda multi-moneda ready", why: "Preparada para integrar pagos y envíos internacionales." },
        { title: "Materiales de marca", why: "Coherencia visual al exportar — confianza en mercados nuevos." },
      ],
    },
  ];

  items.forEach(function (p) {
    window.SALA_CERO_PRODUCTOS.bySlug[p.slug] = p;
    window.SALA_CERO_PRODUCTOS.byName[p.catalogName] = p;
  });
})();
